import 'dart:math' as math;

import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class AdminExportPdf {
  static const PdfColor _accent = PdfColor.fromInt(0xFF334155);

  // The default PDF base font (Helvetica) has no ₱ glyph, so it silently
  // drops the peso sign — fall back to Noto Sans (which does have it) only
  // for characters Helvetica can't draw, so normal text is unaffected.
  static Future<pw.ThemeData>? _themeFuture;
  static Future<pw.ThemeData> _loadTheme() {
    return _themeFuture ??= PdfGoogleFonts.notoSansRegular().then(
      (font) => pw.ThemeData.withFont(fontFallback: [font]),
    );
  }

  /// The first export in a session pays for a Google Fonts network fetch
  /// plus decoding the 3 letterhead logos — call this (fire-and-forget) as
  /// soon as an export-capable page loads so that cost is already paid by
  /// the time the admin actually clicks Export, instead of the button
  /// appearing to freeze.
  static void warmUp() {
    _loadTheme();
    _loadImage('assets/images/bsu_logo.png');
    _loadImage('assets/images/cict_logo.png');
    _loadImage('assets/images/logo.png');
  }

  /// Letterhead: UPRISE + CICT + BSU logos above a brand accent rule and a
  /// small-caps institution line. Admin exports span multiple orgs, so no
  /// single org logo is shown here (see OrgExportPdf for the org-scoped
  /// equivalent that does include one).
  static pw.Widget _brandHeader({
    required pw.MemoryImage? upriseLogo,
    required pw.MemoryImage? cictLogo,
    required pw.MemoryImage? bsuLogo,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 22),
      child: pw.Column(
        children: [
          pw.Row(
            mainAxisSize: pw.MainAxisSize.min,
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              if (upriseLogo != null) pw.Image(upriseLogo, height: 34),
              if (upriseLogo != null && bsuLogo != null) pw.SizedBox(width: 16),
              if (bsuLogo != null) pw.Image(bsuLogo, height: 46),
              if ((upriseLogo != null || bsuLogo != null) && cictLogo != null)
                pw.SizedBox(width: 16),
              if (cictLogo != null) pw.Image(cictLogo, height: 38),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Container(height: 2, width: double.infinity, color: _accent),
          pw.SizedBox(height: 6),
          pw.Text(
            'BULACAN STATE UNIVERSITY  |  COLLEGE OF INFORMATION AND COMMUNICATIONS TECHNOLOGY',
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(
              fontSize: 7,
              color: PdfColors.grey600,
              letterSpacing: 0.6,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _brandFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 14),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Container(
            height: 0.75,
            width: double.infinity,
            color: PdfColors.grey300,
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Uprise - CICT Administration System',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(
                  fontSize: 8.5,
                  color: PdfColors.grey600,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Letterhead-style title block: small-caps eyebrow label, bold title,
  /// optional subtitle, a short accent underline, then the generated-at
  /// timestamp.
  static pw.Widget _titleBlock({
    required String eyebrow,
    required String title,
    String? subtitle,
    required String generatedAt,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          eyebrow,
          style: pw.TextStyle(
            fontSize: 9,
            color: _accent,
            fontWeight: pw.FontWeight.bold,
            letterSpacing: 2.2,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          title,
          textAlign: pw.TextAlign.center,
          style: pw.TextStyle(
            fontSize: 23,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey900,
          ),
        ),
        if (subtitle != null && subtitle.isNotEmpty) ...[
          pw.SizedBox(height: 5),
          pw.Text(
            subtitle,
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
        pw.SizedBox(height: 10),
        pw.Container(width: 64, height: 2.2, color: _accent),
        pw.SizedBox(height: 10),
        pw.Text(
          'Generated $generatedAt',
          style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
        ),
      ],
    );
  }

  static Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String subtitle = 'Official administrative records export',
  }) async {
    final pdf = pw.Document(theme: await _loadTheme());
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final now = DateFormat('MMMM d, yyyy \'at\' h:mm a').format(DateTime.now());
    final pageFormat = headers.length > 5
        ? PdfPageFormat.a4.landscape
        : PdfPageFormat.a4;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: pageFormat,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 28),
        header: (context) => _brandHeader(
          upriseLogo: upriseLogo,
          cictLogo: cictLogo,
          bsuLogo: bsuLogo,
        ),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          pw.Center(
            child: _titleBlock(
              eyebrow: 'EXPORTED RECORD',
              title: title,
              subtitle: subtitle,
              generatedAt: now,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
            margin: const pw.EdgeInsets.only(bottom: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Text(
              '${rows.length} record${rows.length == 1 ? '' : 's'}',
              style: pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey700,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Table(
            border: const pw.TableBorder(
              horizontalInside: pw.BorderSide(
                color: PdfColors.grey300,
                width: 0.5,
              ),
            ),
            defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
            columnWidths: {
              for (var i = 0; i < headers.length; i++)
                i: pw.FlexColumnWidth(
                  headers[i].length.toDouble().clamp(8, 22),
                ),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                  color: _accent,
                  borderRadius: pw.BorderRadius.vertical(
                    top: pw.Radius.circular(4),
                  ),
                ),
                children: headers.map((header) {
                  return pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(
                      vertical: 10,
                      horizontal: 8,
                    ),
                    child: pw.Text(
                      header.toUpperCase(),
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 9,
                        color: PdfColors.white,
                        letterSpacing: 0.4,
                      ),
                      textAlign: pw.TextAlign.center,
                    ),
                  );
                }).toList(),
              ),
              ...rows.asMap().entries.map((entry) {
                final row = entry.value;
                final index = entry.key;
                return pw.TableRow(
                  decoration: index.isEven
                      ? const pw.BoxDecoration(color: PdfColors.orange50)
                      : null,
                  children: List.generate(headers.length, (cellIndex) {
                    final value = cellIndex < row.length ? row[cellIndex] : '';
                    return pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(
                        vertical: 9,
                        horizontal: 8,
                      ),
                      child: pw.Text(
                        value,
                        style: pw.TextStyle(
                          fontSize: 9.5,
                          color: PdfColors.grey900,
                        ),
                      ),
                    );
                  }),
                );
              }),
            ],
          ),
          if (rows.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 20),
              child: pw.Center(
                child: pw.Text(
                  'No records to display.',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey500,
                    fontStyle: pw.FontStyle.italic,
                  ),
                ),
              ),
            ),
        ],
      ),
    );

    return pdf.save();
  }

  /// Stamps the admin's drawn signature onto the actual last page of the
  /// org's submitted PDF, instead of producing a separate certificate.
  ///
  /// There's no package in this project that can load and edit an existing
  /// PDF's pages directly (`pdf`/`pw.Document` only builds new documents
  /// from scratch). Instead, this rasterizes every page of the original PDF
  /// to an image via `printing`'s `Printing.raster()` (already a dependency,
  /// works on web via a bundled pdf.js) and rebuilds a new PDF where each
  /// page is that image at full bleed — with the signature overlaid on the
  /// last page. Visually identical to the original, but with a real stamp
  /// on the actual document instead of a bolted-on cover sheet.
  static const double _signatureStampWidth = 170;

  /// [xPct]/[yPct] are the drag position (0..1 of the last page's own
  /// width/height) an admin picked in the on-screen preview, marking the
  /// center of where the signature block should land — matching the same
  /// percentage-of-page approach org_certificates.dart uses for its
  /// signatory placements, so the position transfers correctly regardless
  /// of what DPI the preview vs. the final stamp were rasterized at. Left
  /// null (e.g. no legacy call site passes them), the original fixed
  /// bottom-right spot is kept as-is.
  static Future<Uint8List> stampSignatureOnPdf({
    required Uint8List originalPdfBytes,
    required Uint8List signatureBytes,
    required String signedByName,
    required DateTime signedAt,
    String remark = '',
    String role = 'Admin, Uprise',
    double? xPct,
    double? yPct,
  }) async {
    // 110 DPI keeps the stamped copy legible while meaningfully cutting the
    // raster + re-encode work for multi-page documents (this whole pipeline
    // runs on the UI thread on web, so fewer pixels = less visible freeze).
    const dpi = 110.0;
    final rasterPages = await Printing.raster(
      originalPdfBytes,
      dpi: dpi,
    ).toList();
    if (rasterPages.isEmpty) {
      throw Exception('Could not read the original document pages.');
    }

    final pdf = pw.Document(theme: await _loadTheme());
    final signatureImage = pw.MemoryImage(signatureBytes);

    for (var i = 0; i < rasterPages.length; i++) {
      final raster = rasterPages[i];
      final pageImage = pw.MemoryImage(await raster.toPng());
      final pageWidthPts = raster.width / dpi * PdfPageFormat.inch;
      final pageHeightPts = raster.height / dpi * PdfPageFormat.inch;
      final pageFormat = PdfPageFormat(pageWidthPts, pageHeightPts);
      final isLastPage = i == rasterPages.length - 1;

      // Roughly matches _signatureOverName's own rendered height (56px
      // signature + ~50px of name/role/timestamp text beneath it) — only
      // used to keep the dragged drop point centered on the stamp instead
      // of anchored at its corner.
      const stampHeight = 90.0;
      final double? stampLeft = xPct == null
          ? null
          : (xPct * pageWidthPts - _signatureStampWidth / 2)
                .clamp(0.0, math.max(0.0, pageWidthPts - _signatureStampWidth))
                .toDouble();
      final double? stampTop = yPct == null
          ? null
          : (yPct * pageHeightPts - stampHeight / 2)
                .clamp(0.0, math.max(0.0, pageHeightPts - stampHeight))
                .toDouble();

      pdf.addPage(
        pw.Page(
          pageFormat: pageFormat,
          margin: pw.EdgeInsets.zero,
          build: (context) => pw.Stack(
            overflow: pw.Overflow.visible,
            children: [
              pw.Positioned.fill(
                child: pw.Image(pageImage, fit: pw.BoxFit.fill),
              ),
              if (isLastPage)
                pw.Positioned(
                  left: stampLeft,
                  top: stampTop,
                  right: stampLeft == null ? 36 : null,
                  bottom: stampTop == null ? 48 : null,
                  child: _signatureOverName(
                    signatureImage: signatureImage,
                    signedByName: signedByName,
                    signedAt: signedAt,
                    remark: remark,
                    role: role,
                  ),
                ),
            ],
          ),
        ),
      );
    }

    return pdf.save();
  }

  /// Signature ink rendered overlapping down onto the printed name beneath
  /// it — like a real signed document — instead of sitting in its own
  /// separate box above a line.
  static pw.Widget _signatureOverName({
    required pw.MemoryImage signatureImage,
    required String signedByName,
    required DateTime signedAt,
    String role = 'Admin, Uprise',
    double width = 170,
    bool showTimestamp = true,
    String remark = '',
  }) {
    return pw.Row(
      mainAxisSize: pw.MainAxisSize.min,
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.SizedBox(
          width: width,
          child: pw.Stack(
            alignment: pw.Alignment.topCenter,
            overflow: pw.Overflow.visible,
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.only(top: 28),
                child: pw.Column(
                  children: [
                    pw.Container(
                      height: 0.8,
                      width: width - 10,
                      color: PdfColors.grey500,
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      signedByName,
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey900,
                      ),
                      textAlign: pw.TextAlign.center,
                    ),
                    pw.Text(
                      role,
                      style: pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.grey600,
                      ),
                    ),
                    if (showTimestamp) ...[
                      pw.SizedBox(height: 2),
                      pw.Text(
                        'Digitally signed on ${DateFormat('MMM d, yyyy h:mm a').format(signedAt)}',
                        style: pw.TextStyle(
                          fontSize: 6.5,
                          color: PdfColors.grey500,
                          fontStyle: pw.FontStyle.italic,
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              pw.Positioned(
                top: -8,
                child: pw.SizedBox(
                  height: 48,
                  width: width - 20,
                  child: pw.Image(signatureImage, fit: pw.BoxFit.contain),
                ),
              ),
            ],
          ),
        ),
        if (remark.trim().isNotEmpty) ...[
          pw.SizedBox(width: 14),
          pw.Container(
            width: width * 0.85,
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(5),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Text(
                  'REMARK',
                  style: pw.TextStyle(
                    fontSize: 6.5,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey600,
                    letterSpacing: 0.5,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  remark.trim(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.grey900,
                    fontStyle: pw.FontStyle.italic,
                  ),
                ),
              ],
            ),
          ),
        ],
      ],
    );
  }

  static pw.Widget _signedRow(String label, String value) => pw.Padding(
    padding: const pw.EdgeInsets.symmetric(vertical: 4),
    child: pw.Row(
      children: [
        pw.SizedBox(
          width: 110,
          child: pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
        pw.Expanded(
          child: pw.Text(
            value,
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey900),
          ),
        ),
      ],
    ),
  );

  /// One-page certificate proving a letter request was reviewed and
  /// digitally signed — the drawn signature is embedded as an image, plus
  /// who signed it and when. This is what "e-sign" produces in place of the
  /// old in-person wet-sign appointment scheduling.
  static Future<Uint8List> generateSignedLetterPdf({
    required String letterId,
    required String subject,
    required String orgName,
    required String requestorName,
    required Uint8List signatureBytes,
    required String signedByName,
    required DateTime signedAt,
    String remark = '',
    // Optional so existing callers keep compiling. These matter for the
    // request types that no longer require the org to attach a draft —
    // without them, an attachment-less request would produce a signed page
    // that never says who the letter is for or what it is for.
    String letterType = '',
    String addressedTo = '',
    String purpose = '',
  }) async {
    final pdf = pw.Document(theme: await _loadTheme());
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final signatureImage = pw.MemoryImage(signatureBytes);
    final now = DateFormat('MMMM d, yyyy \'at\' h:mm a').format(signedAt);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(36, 32, 36, 32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _brandHeader(
              upriseLogo: upriseLogo,
              cictLogo: cictLogo,
              bsuLogo: bsuLogo,
            ),
            pw.Center(
              child: _titleBlock(
                eyebrow: 'LETTER APPROVAL',
                title: 'E-Signature Certificate',
                subtitle:
                    'This certifies that the letter request below has been reviewed and approved.',
                generatedAt: now,
              ),
            ),
            pw.SizedBox(height: 24),
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey50,
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  _signedRow('Letter ID', letterId),
                  if (letterType.isNotEmpty) _signedRow('Type', letterType),
                  _signedRow('Subject', subject),
                  if (addressedTo.isNotEmpty)
                    _signedRow('Addressed to', addressedTo),
                  if (purpose.isNotEmpty) _signedRow('Purpose', purpose),
                  _signedRow('Organization', orgName),
                  _signedRow('Requested by', requestorName),
                ],
              ),
            ),
            pw.SizedBox(height: 40),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                _signatureOverName(
                  signatureImage: signatureImage,
                  signedByName: signedByName,
                  signedAt: signedAt,
                  role: 'Authorized Signatory',
                  width: 200,
                  showTimestamp: false,
                  remark: remark,
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                    horizontal: 14,
                    vertical: 8,
                  ),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.green700, width: 2),
                    borderRadius: pw.BorderRadius.circular(6),
                  ),
                  child: pw.Text(
                    'APPROVED',
                    style: pw.TextStyle(
                      color: PdfColors.green700,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 16,
                      letterSpacing: 2,
                    ),
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 10),
            pw.Text(
              'Digitally signed on $now',
              style: pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey500,
                fontStyle: pw.FontStyle.italic,
              ),
            ),
          ],
        ),
      ),
    );

    return pdf.save();
  }

  // Logos never change at runtime — cache them once per app session instead
  // of re-decoding from the asset bundle on every export call.
  static final Map<String, Future<pw.MemoryImage?>> _imageCache = {};

  static Future<pw.MemoryImage?> _loadImage(String path) {
    return _imageCache.putIfAbsent(path, () => _loadImageUncached(path));
  }

  static Future<pw.MemoryImage?> _loadImageUncached(String path) async {
    try {
      final byteData = await rootBundle.load(path);
      final rawBytes = byteData.buffer.asUint8List();

      // These logos render at ~34-46pt tall in the letterhead, but the
      // bundled PNGs are kept at full app-icon resolution (400-600KB each)
      // for crisp display elsewhere in the app (sidebar, login page).
      // Embedding all that unused resolution into every generated PDF was
      // most of what made pdf.save() slow — downscale a copy just for PDF
      // use instead of touching the shared asset.
      final decoded = img.decodeImage(rawBytes);
      if (decoded == null) return pw.MemoryImage(rawBytes);

      const maxDimension = 300;
      if (decoded.width <= maxDimension && decoded.height <= maxDimension) {
        return pw.MemoryImage(rawBytes);
      }
      final resized = img.copyResize(
        decoded,
        width: decoded.width >= decoded.height ? maxDimension : null,
        height: decoded.height > decoded.width ? maxDimension : null,
      );
      return pw.MemoryImage(Uint8List.fromList(img.encodePng(resized)));
    } catch (_) {
      return null;
    }
  }
}
